### ISSUE TITLE
State

### ISSUE THREAD

**Issue by wwboynton** [hired/limitless-led#2]
Hey! Thanks for writing this library! It's a really slick interface to these bulbs.

Does this gem provide a way to read state from the bulbs? I can't find anything about getting state in the API docs, but it seems like OpenHAB has the ability to do operations like "TOGGLE" which would indicate there's some way to read state from the bulbs and react to it. 

Cheers!

**Comment by heythisisnate** [comment]
No, as far as I know, there is no way to read state from the lights. The commands are all one way UDP packets sent to the bridge, there is no two way communication.
